version: '2'
services:
  bitcoind:
    image: andgo/bitcoind
    build: "./bitcoind"
    ports:
      - "3001:3000"
    expose:
      - "18443"
    volumes:
      - ./data/bitcoind:/home/bitcoin/.bitcoin

  electrumx:
    image: lukechilds/electrumx
    ports:
      - "55002:50002"
    volumes:
      - ./data/electrumx:/data
    environment:
      - DAEMON_URL=http://electrum:electrum@bitcoind:18443
      - COIN=BitcoinSegwit
      - NET=regtest
      - RPC_HOST=127.0.0.1
